title: Vítor Fonseca
logo: docs/assets/me.vf.png
description: I am a final-year BSc student in Aerospace Engineering at Instituto Superior Técnico (IST Lisboa), where I focus on robotic systems. I am currently a team member of SocRob@Home at the Institute for Systems and Robotics (ISR Lisboa), and I manage the Autonomous Systems department of Técnico Fuel Cell (TFC), a student-led association. My research at ISR focuses on Embodied AI using Visual Language Models (VLMs) and 3D point cloud reconstruction.
remote_theme: pages-themes/minimal@v0.2.0
linkedin_url: https://www.linkedin.com/in/vitor-hugo-fonseca/
github_url: https://github.com/vitorhcf
cv_url: /docs/assets/cv.pdf
plugins:
- jekyll-remote-theme
projects:
  - title: Semantic Reconstruction
    description: Demo for filtering and surface identification from point clouds generated in simulation. The Open3D pipeline also generates a 3D mesh reconstruction of specific surfaces that are important for manipulation tasks at RoboCup 2026. I am also working on designing and fine-tuning a deep neural network to filter noisy real-world point clouds and perform accurate 3D object detection. The goal is to apply Edge AI techniques so it can run in real time on the robot's local computer.
    gif: docs/assets/pcl.gif
    link_text: View project
    link_url: https://isr.tecnico.ulisboa.pt/projects_cat/irsg/ 
  - title: AV Gazebo Simulation
    description: Gazebo simulation designed to model sensors, actuators, and the track in order to validate the car's autonomy stack. The work included URDF, Gazebo controllers, a detection model, architecture optimization, sensor design, and calibration.
    gif: docs/assets/gazebotrim.gif
    link_text: View project
    link_url: https://tfcell.tecnico.ulisboa.pt/
  - title: Manipulator AMR
    description: Personal project focused on designing an Autonomous Mobile Robot with manipulation capabilities. The goal is to expand my knowledge of reinforcement learning techniques for autonomous driving and manipulation.
    gif: 
    media:
      - docs/assets/mr1.jpeg
      - docs/assets/mr2.jpeg
      - docs/assets/mr3.jpeg
    link_text: View project
    link_url: https://github.com/vitorhcf/Manipulator-AMR 
  - title: VLM ROS2 bridge and optimization
    description: Visual Language Model (Chatrex) ROS 2 bridge. This project demonstrates object detection with real-time performance. The prompt is "Please detect chairs; sofas; sitting people in this image. List each one with a different object index." As shown, the model successfully outputs the bounding boxes for the requested prompt in under 1 second. The process uses cloud AI to run the model and then sends the inference results to the robot running ROS 2.
    gif: docs/assets/chatrex.gif
    media:
      - docs/assets/output_inference.jpg
    link_text: View project
    link_url: https://github.com/IDEA-Research/ChatRex
  - title: Drone Prototyping
    description: Quadrotor design, from avionics to CAD and manufacturing. The drone was designed for autonomous rescue applications, detecting a person and bridging communication with support services.
    gif: docs/assets/atlas.gif
    media:
      - docs/assets/scheme.jpeg
      - docs/assets/drone_cad.jpeg
      - docs/assets/atlas.gif
    link_text: View project
    link_url: https://aerotec.pt/atlas
